[build-system]
requires = [
  "setuptools",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true
skip-magic-trailing-comma = true
exclude = ''